networks:
  integration-test:

services:
  it_tests:
    build:
      context: .
      dockerfile: ./Dockerfile.it
    environment:
      - DOCKER_DATABASE_POSTGRES_URI=postgres://todoadmin123:admin!@db:5432/todo_app?sslmode=disable
    volumes:
      - $PWD:/go/src
    depends_on:
      db:
        condition: service_healthy
    networks:
      - integration-test

  db:
    image: postgres:16.2
    user: postgres
    environment:
      POSTGRES_USER: todoadmin123
      POSTGRES_PASSWORD: admin!
      POSTGRES_DB: todo_app
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - integration-test

volumes:
  db-data:
