FROM golang:1.22.3-alpine AS builder

WORKDIR /go/src

COPY go.mod go.sum ./

RUN CGO_ENABLED=0 go mod download

FROM golang:1.21.9-alpine AS runtime

COPY --from=builder /go/pkg /go/pkg

WORKDIR /go/src

CMD CGO_ENABLED=0 go test -v run "Test.*IT" -tags=integration ./...
